language: python
python:
  - 2.7
install:
  - python bootstrap.py
  - bin/buildout -N
script:
  - bin/test -s Products.CMFPlomino
notifications:
  irc:
    - "irc.freenode.org#plomino"
  email:
    - eric.brehault@makina-corpus.com
