language: python
env:
  - PLONE_VERSION=4.0
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
python:
  - 2.7
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - echo Add good-py versions for plone.app.registry for Plone 4.0
  - if [ "$PLONE_VERSION" == "4.0" ] ; then sed "4 a\    http://good-py.appspot.com/release/plone.app.registry/1.0b2?plone=4.0.9" travis.cfg > travis.cfg.new && mv travis.cfg{.new,}  ; fi
  - if [ "$PLONE_VERSION" == "4.1" ] ; then sed "4 a\    http://good-py.appspot.com/release/plone.app.registry/1.0b2?plone=4.1.6" travis.cfg > travis.cfg.new && mv travis.cfg{.new,}  ; fi
  - if [ "$PLONE_VERSION" == "4.1" ] ; then echo plone.app.testing=4.2.2 >> travis.cfg ; fi
  - cat travis.cfg # Debug
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/test --coverage -m Products.CMFPlomino
notifications:
  irc:
    - "irc.freenode.org#plomino"
